name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'tests'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'tests'

jobs:
  build:
    name: Build Library

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make library
      run: |
          make -j$(nproc) library